language: node_js
node_js:
  # https://github.com/nodejs/LTS
  - "4" # ends April 2018
  - "6" # ends April 2019
  - "8" # ends December 2019

sudo: false

cache:
  directories:
  - node_modules

env:
  global:
    - SAUCE_USERNAME=sinonjs
    - secure: "T0/TMZgx6NoqtAj8hvXUp1WGLdeqQR01EEWY/cvhJBv54dBLCvcIqEwBmG7w3shPmBMvFsvfrSgXqnoGeHm1dep7kanA1XfK4/OaDSfuBlFFVgIvwQph/lPqUBAHGItk/g+ky9OwJL2mNpTJmTNsf8/HulueDuRK9pUr/t98KxQ="

before_install:
  - npm config set strict-ssl false
  - npm install coveralls

before_script:
  # these build targets only need to run once per build, so let's conserve a few resources
  # ESLint only supports Node >=4
  - if [ "x$TRAVIS_NODE_VERSION" = "x6" ]; then npm run lint; fi
  # run these on node 6 to have npm 3 with flat dependencies
  - if [ "x$TRAVIS_NODE_VERSION" = "x6" ]; then npm run test-headless; fi
  - if [ "x$TRAVIS_NODE_VERSION" = "x6" ]; then npm run test-webworker; fi
  - if [ "x$TRAVIS_NODE_VERSION" = "x6" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test-cloud; fi

script:
  - npm run test-node

after_success:
  - npm run test-coverage
  - cat ./coverage/lcov.info | coveralls lib

git:
  depth: 10
