title: Sinon.JS
description: >-
  Standalone test spies, stubs and mocks for JavaScript. Works with any unit
  testing framework.
url: 'http://sinonjs.org'
github_username: sinonjs
sinon:
  current_release: v5.0.0-next.3
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - release-source
collections:
  howto:
    output: true
    permalink: '/how-to/:path/'
  releases:
    output: true
    permalink: '/:collection/:path/'
sass:
  sass_dir: _sass
  style: compressed
