title: Sinon.JS
description: >-
  Standalone test spies, stubs and mocks for JavaScript. Works with any unit
  testing framework.
url: 'https://sinonjs.org'
github_username: sinonjs
sinon:
  current_release: v7.2.2
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
keep_files:
  - assets
  - releases
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - release-source
collections:
  howto:
    output: true
    permalink: '/how-to/:path/'
  releases:
    output: true
    permalink: '/:collection/:path/'
sass:
  sass_dir: _sass
  style: compressed
